name: coastal_tourism_app
description: A mobile app for coastal tourism suitability.

publish_to: "none" # Set to none if you're not publishing this package.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0" # Ensure this matches your current Dart SDK.

dependencies:
  flutter:
    sdk: flutter
  provider: any # Latest version
  http: any  # Latest version
  cupertino_icons: ^1.0.5  # Latest stable version
  flutter_riverpod: any # Latest version
  google_maps_flutter: ^2.7.0  # Latest stable version
  flutter_spinkit: ^5.2.1
  location: ^7.0.0
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.2
  flutter_staggered_animations: ^1.1.1
  weather_icons: ^3.0.0
  cached_network_image: ^3.2.0
  geocoding: ^3.0.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any  # Latest version
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true
